# Generated by Django 6.0.5 on 2026-05-11 10:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mechanics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PremiumContactRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requester_name', models.CharField(max_length=150)),
                ('requester_phone', models.CharField(max_length=20)),
                ('requester_reason', models.TextField()),
                ('requester_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('requester_user_agent', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvée'), ('rejected', 'Rejetée'), ('expired', 'Expirée')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('contact_revealed_at', models.DateTimeField(blank=True, null=True)),
                ('contact_reveal_count', models.PositiveSmallIntegerField(default=0)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_requests', to='mechanics.mechanicprofile')),
                ('requester_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='premium_contact_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'premium_contact_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mechanic', 'status'], name='premium_con_mechani_93d125_idx'), models.Index(fields=['requester_ip'], name='premium_con_request_736a7e_idx'), models.Index(fields=['created_at'], name='premium_con_created_d130cd_idx')],
            },
        ),
    ]
