# Generated by Django 6.0.5 on 2026-05-11 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breakdowns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending_acceptance', "En attente d'acceptation"), ('accepted', 'Acceptée'), ('refused', 'Refusée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('disputed', 'Litigieuse'), ('cancelled', 'Annulée')], default='pending_acceptance', max_length=25)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('refused_at', models.DateTimeField(blank=True, null=True)),
                ('refusal_reason', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('mechanic_notes', models.TextField(blank=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('before_photo', models.FileField(blank=True, null=True, upload_to='interventions/photos/')),
                ('after_photo', models.FileField(blank=True, null=True, upload_to='interventions/photos/')),
                ('breakdown_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='intervention', to='breakdowns.breakdownrequest')),
            ],
            options={
                'db_table': 'interventions_intervention',
                'ordering': ['-created_at'],
            },
        ),
    ]
