# Generated by Django 6.0.5 on 2026-05-11 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interventions', '0001_initial'),
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interventions', to='mechanics.mechanicprofile'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['status'], name='interventio_status_b4f56c_idx'),
        ),
        migrations.AddIndex(
            model_name='intervention',
            index=models.Index(fields=['mechanic', 'status'], name='interventio_mechani_ea492e_idx'),
        ),
    ]
