# Generated by Django 5.2.14 on 2026-06-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0003_intervention_driver_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='status',
            field=models.CharField(choices=[('pending_acceptance', "En attente d'acceptation"), ('accepted', 'Acceptée'), ('refused', 'Refusée'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('paid', 'Payée'), ('reviewed', 'Évaluée'), ('cancelled', 'Annulée')], default='pending_acceptance', max_length=25),
        ),
    ]
