# Generated by Django 5.2.14 on 2026-06-09 22:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interventions', '0005_intervention_fk_broadcast'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervention',
            name='after_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='after_photo'),
        ),
        migrations.AlterField(
            model_name='intervention',
            name='before_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='before_photo'),
        ),
    ]
