# Generated by Django 5.2.14 on 2026-06-09 21:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interventions', '0005_intervention_fk_broadcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('emitter_type', models.CharField(choices=[('driver', 'Conducteur'), ('mechanic', 'Mécanicien')], max_length=20)),
                ('emitter_name', models.CharField(max_length=200)),
                ('target_name', models.CharField(max_length=200)),
                ('incident_type', models.CharField(choices=[('abuse', 'Abus de langage'), ('delay', 'Retard important'), ('price', 'Problème de prix'), ('fraud', 'Fraude'), ('quality', 'Qualité du service'), ('other', 'Autre')], default='other', max_length=50)),
                ('gravity', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé')], default='low', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('resolved', 'Résolu'), ('rejected', 'Rejeté'), ('suspended', 'Suspendu')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, help_text='Note interne admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidents', to='interventions.intervention')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
