# Generated by Django 5.2.14 on 2026-06-11 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='incident_type',
            field=models.CharField(choices=[('abuse', 'Abus de langage'), ('delay', 'Retard important'), ('price', 'Problème de prix'), ('fraud', 'Fraude'), ('quality', 'Qualité du service'), ('review', 'Avis litigieux'), ('other', 'Autre')], default='other', max_length=50),
        ),
    ]
