# Generated by Django 6.0.5 on 2026-05-11 10:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breakdowns', '0001_initial'),
        ('interventions', '0001_initial'),
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payer_name', models.CharField(max_length=150)),
                ('payer_phone', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='XOF', max_length=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_for', models.CharField(choices=[('intervention', 'Intervention standard'), ('premium_subscription', 'Abonnement premium')], max_length=30)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('authorized', 'Autorise'), ('paid', 'Paye'), ('failed', 'Echoue'), ('refunded', 'Rembourse'), ('cancelled', 'Annule')], default='pending', max_length=20)),
                ('provider_reference', models.CharField(blank=True, max_length=120)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('breakdown_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='breakdowns.breakdownrequest')),
                ('intervention', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='interventions.intervention')),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='mechanics.mechanicprofile')),
            ],
            options={
                'db_table': 'payments_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='payments_tr_status_96e6c0_idx'), models.Index(fields=['payment_for'], name='payments_tr_payment_3ee565_idx'), models.Index(fields=['payer_phone'], name='payments_tr_payer_p_ad8f5c_idx'), models.Index(fields=['provider_reference'], name='payments_tr_provide_9bbfff_idx')],
            },
        ),
    ]
