# Generated by Django 5.2.14 on 2026-06-09 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0010_vehicle_type_brand'),
        ('interventions', '0005_intervention_fk_broadcast'),
        ('mechanics', '0007_mc_short_id_format'),
        ('payments', '0002_wallet_and_withdrawals'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymenttransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference__gt', '')), fields=('breakdown_request', 'provider_reference'), name='unique_breakdown_fedapay_transaction'),
        ),
    ]
