# Generated by Django 6.0.5 on 2026-05-11 10:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakdownRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('driver_name', models.CharField(max_length=150)),
                ('driver_phone', models.CharField(max_length=20)),
                ('driver_id_card', models.FileField(upload_to='breakdowns/id_cards/')),
                ('driver_selfie', models.FileField(upload_to='breakdowns/selfies/')),
                ('vehicle_description', models.CharField(max_length=200)),
                ('vehicle_photo', models.FileField(upload_to='breakdowns/vehicles/')),
                ('breakdown_description', models.TextField()),
                ('breakdown_type', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('address_description', models.TextField(blank=True)),
                ('assignment_distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('assigned', 'Mécanicien assigné'), ('in_progress', 'En cours'), ('completed', 'Terminée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'breakdowns_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
