# Generated by Django 6.0.5 on 2026-05-11 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breakdowns', '0001_initial'),
        ('mechanics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdownrequest',
            name='assigned_mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_breakdowns', to='mechanics.mechanicprofile'),
        ),
        migrations.AddField(
            model_name='breakdownrequest',
            name='driver_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='breakdown_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='breakdownrequest',
            name='specialty_requested',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mechanics.specialty'),
        ),
        migrations.AddIndex(
            model_name='breakdownrequest',
            index=models.Index(fields=['status'], name='breakdowns__status_79680e_idx'),
        ),
        migrations.AddIndex(
            model_name='breakdownrequest',
            index=models.Index(fields=['driver_phone'], name='breakdowns__driver__af36c2_idx'),
        ),
        migrations.AddIndex(
            model_name='breakdownrequest',
            index=models.Index(fields=['assigned_mechanic'], name='breakdowns__assigne_20fb57_idx'),
        ),
        migrations.AddIndex(
            model_name='breakdownrequest',
            index=models.Index(fields=['created_at'], name='breakdowns__created_ffbe95_idx'),
        ),
    ]
