# Generated by Django 5.2.14 on 2026-06-04 00:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_type', models.CharField(choices=[('driver', 'Conducteur'), ('mechanic', 'Mécanicien')], max_length=10)),
                ('sender_name', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('breakdown_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='breakdowns.breakdownrequest')),
            ],
            options={
                'db_table': 'breakdowns_message',
                'ordering': ['created_at'],
            },
        ),
    ]
