# Generated by Django 5.2.14 on 2026-06-04 13:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0003_add_message_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdownrequest',
            name='driver_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
