# Generated by Django 5.2.14 on 2026-06-04 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0004_add_driver_token_and_paid_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('driver', 'Conducteur'), ('mechanic', 'Mécanicien'), ('admin', 'Administrateur')], max_length=10),
        ),
    ]
