# Generated by Django 5.2.14 on 2026-06-07 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0006_breakdown_refusal_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdownrequest',
            name='driver_phone',
            field=models.CharField(max_length=15),
        ),
    ]
