# Generated by Django 5.2.14 on 2026-06-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0007_phone_maxlength_15'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdownrequest',
            name='breakdown_type',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
