# Generated by Django 5.2.14 on 2026-06-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0008_breakdown_type_maxlength_500'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdownrequest',
            name='phase_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breakdownrequest',
            name='search_phase',
            field=models.IntegerField(default=1),
        ),
    ]
