# Generated by Django 5.2.14 on 2026-06-09 22:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0010_vehicle_type_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdownrequest',
            name='driver_id_card',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='driver_id_card'),
        ),
        migrations.AlterField(
            model_name='breakdownrequest',
            name='driver_selfie',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='driver_selfie'),
        ),
        migrations.AlterField(
            model_name='breakdownrequest',
            name='vehicle_photo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='vehicle_photo'),
        ),
    ]
