# Generated by Django 5.2.14 on 2026-06-11 13:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0011_alter_breakdownrequest_driver_id_card_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakdownrequest',
            name='driver_id_card',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='driver_id_card'),
        ),
        migrations.AlterField(
            model_name='breakdownrequest',
            name='driver_selfie',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='driver_selfie'),
        ),
    ]
