# Generated by Django 5.2.14 on 2026-07-14 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakdowns', '0012_driver_id_card_selfie_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdownrequest',
            name='is_agglomeration',
            field=models.BooleanField(default=False),
        ),
    ]
