# Generated by Django 6.0.5 on 2026-05-11 10:15

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interventions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Specialties',
                'db_table': 'mechanics_specialty',
            },
        ),
        migrations.CreateModel(
            name='MechanicProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True)),
                ('years_experience', models.PositiveSmallIntegerField(default=0)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(default='Bénin', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
                ('available_from', models.TimeField(blank=True, null=True)),
                ('available_to', models.TimeField(blank=True, null=True)),
                ('works_weekends', models.BooleanField(default=True)),
                ('id_card_front', models.FileField(blank=True, null=True, upload_to='mechanics/id_cards/')),
                ('id_card_back', models.FileField(blank=True, null=True, upload_to='mechanics/id_cards/')),
                ('certification_doc', models.FileField(blank=True, null=True, upload_to='mechanics/certifications/')),
                ('profile_photo', models.FileField(blank=True, null=True, upload_to='mechanics/photos/')),
                ('status', models.CharField(choices=[('pending', 'En attente de validation'), ('approved', 'Approuvé'), ('rejected', 'Rejeté'), ('suspended', 'Suspendu')], default='pending', max_length=20)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('total_interventions', models.PositiveIntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mechanic_profile', to=settings.AUTH_USER_MODEL)),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_mechanics', to=settings.AUTH_USER_MODEL)),
                ('specialties', models.ManyToManyField(blank=True, related_name='mechanics', to='mechanics.specialty')),
            ],
            options={
                'db_table': 'mechanics_profile',
            },
        ),
        migrations.CreateModel(
            name='MechanicReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer_name', models.CharField(max_length=100)),
                ('reviewer_phone_hash', models.CharField(blank=True, max_length=64)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('intervention', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='interventions.intervention')),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='mechanics.mechanicprofile')),
            ],
            options={
                'db_table': 'mechanics_review',
                'indexes': [models.Index(fields=['mechanic', 'is_visible'], name='mechanics_r_mechani_b7e9c6_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='mechanicprofile',
            index=models.Index(fields=['status'], name='mechanics_p_status_8608d5_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanicprofile',
            index=models.Index(fields=['is_available'], name='mechanics_p_is_avai_c5243e_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanicprofile',
            index=models.Index(fields=['latitude', 'longitude'], name='mechanics_p_latitud_2ee13c_idx'),
        ),
        migrations.AddIndex(
            model_name='mechanicprofile',
            index=models.Index(fields=['city'], name='mechanics_p_city_6f6b78_idx'),
        ),
    ]
