# Generated by Django 5.2.14 on 2026-06-04 15:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MechanicAdminMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender_type', models.CharField(choices=[('mechanic', 'Mécanicien'), ('admin', 'Administrateur')], max_length=10)),
                ('sender_name', models.CharField(max_length=150)),
                ('content', models.TextField()),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to='mechanics.mechanicprofile')),
            ],
            options={
                'db_table': 'mechanics_admin_message',
                'ordering': ['created_at'],
            },
        ),
    ]
