# Generated by Django 5.2.15 on 2026-06-08 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0003_initial_specialties'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
