# Generated by Django 5.2.15 on 2026-06-08 09:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0004_wallet_and_withdrawals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='withdrawal_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='MomoNumberChangeRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('new_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('mechanic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='momo_change_requests', to='mechanics.mechanicprofile')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_momo_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mechanics_momo_change_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
