# Generated by Django 5.2.15 on 2026-06-08 09:41

import random
from django.db import migrations, models

_CHARS = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'


def populate_short_ids(apps, schema_editor):
    MechanicProfile = apps.get_model('mechanics', 'MechanicProfile')
    used = set(MechanicProfile.objects.exclude(short_id='').values_list('short_id', flat=True))
    for profile in MechanicProfile.objects.filter(short_id=''):
        for _ in range(200):
            sid = ''.join(random.choices(_CHARS, k=8))
            if sid not in used:
                used.add(sid)
                profile.short_id = sid
                profile.save(update_fields=['short_id'])
                break


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0005_add_withdrawal_number_and_momo_change_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='short_id',
            field=models.CharField(blank=True, db_index=True, max_length=8, default=''),
            preserve_default=False,
        ),
        migrations.RunPython(populate_short_ids, migrations.RunPython.noop),
        # AlterField avec db_index=True + unique=True génère deux fois le CREATE INDEX _like
        # sur PostgreSQL (déferred SQL). On ajoute uniquement la contrainte unique en SQL brut.
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="ALTER TABLE mechanics_profile ADD CONSTRAINT mechanics_profile_short_id_key UNIQUE (short_id);",
                    reverse_sql="ALTER TABLE mechanics_profile DROP CONSTRAINT IF EXISTS mechanics_profile_short_id_key;",
                ),
            ],
            state_operations=[
                migrations.AlterField(
                    model_name='mechanicprofile',
                    name='short_id',
                    field=models.CharField(blank=True, db_index=True, max_length=8, unique=True),
                ),
            ],
        ),
    ]
