# Generated by Django 5.2.14 on 2026-06-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0007_mc_short_id_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Département'),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='neighborhood',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Quartier'),
        ),
    ]
