# Generated by Django 5.2.14 on 2026-06-09 22:06

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mechanics', '0008_add_department_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mechanicprofile',
            name='certification_doc',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='certification_doc'),
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='id_card_back',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='id_card_back'),
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='id_card_front',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='id_card_front'),
        ),
        migrations.AlterField(
            model_name='mechanicprofile',
            name='profile_photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_photo'),
        ),
    ]
